name: Assignment-2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - bokeh=2.4.2
  - numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - pip
  - pandas
  - folium
  - ipywidgets
  - matplotlib
  - widgetsnbextension
  - ipython
  - panel
  - ipyleaflet
  - cartopy
  - pip:
      - Flask-Testing
  - jupyter-panel-proxy
